environments:
  dev:
    baseUrl: "https://www.saucedemo.com/"
    timeout: 30000

    # website config
    browser:
      name: "chrome"
      headless: true
      windowSize: "1920x1080"

    # test config
    test:
      retries: 2
      screenshotOnFailure: true
      reportPath: "target/reports"
